### ISSUE TITLE
Recipe #21 (lateral join) is problematic

### ISSUE THREAD

**Issue by alpinegizmo** [ververica/flink-sql-cookbook#30]
Recipe #21 has issues.

This line

        ROW_NUMBER() OVER (PARTITION BY id ORDER BY arrival_time) AS rownum

should be

        ROW_NUMBER() OVER (PARTITION BY id ORDER BY arrival_time DESC) AS rownum

Otherwise it only takes the first arrival for each person, and never considers any of their subsequent moves. This is why the final query as published rather quickly reaches a steady state, and ceases to have updates. It only shows the initial placement of the 100 people, as they are born.

However, the results from this updated query are messy. Once the people start to move around, the number of results displayed in the SQL client begins to rise. While there are 8 results in the beginning (the top 2 for each of the 4 states),  if you leave it running then there are more and more. It's as though it switches from retracting to appending, but I'm not sure what's going on.

Also, I note the animated gif for this example doesn't go very far -- it doesn't show any results.

**Comment by sjwiesman** [comment]
@alpinegizmo thanks for pointing out the issue with the query. I have merged a fix for the window. Regarding the SQL client, I believe its actually an issue with the SQL client visualizing the results and not the query itself. I was able to reproduce what you described in 'table' output mode but saw correct results in 'change-log' mode.

**Comment by alpinegizmo** [comment]
👍
