### ISSUE TITLE
Connector "Faker" doesn't seem to work

### ISSUE THREAD

**Issue by danp11** [ververica/flink-sql-cookbook#33]
Hi and Thanks for this repo, it's very interesting.

I'm trying to execute Day 2 on the community edition of VVP but getting the below error:

![image](https://user-images.githubusercontent.com/6255904/103778188-31431980-5032-11eb-9180-c198ac78e40a.png)

Is it something with my env. or anything else? Please help me troubleshoot. 

Thanks in advance, 

/Dan

**Comment by sjwiesman** [comment]
Hi @danp11 

The faker does not ship with the current version of Ververica Platform. It is something we only recently developed to provide better demo data. The connector is open source and available [here](https://github.com/knaufk/flink-faker). Additionally, you can follow the instructions to add a [custom connector](https://docs.ververica.com/user_guide/sql_development/connectors.html#customizing-packaged-connectors) to the platform.

**Comment by danp11** [comment]
Ah ok, thanks for your quick reply. I think it would be great if you in the readme could give some detailed instructions on how to add the faker connector to the vvp. Im new to vvp so its not so easy to add this connector for me even though you provided the link. Is the SQL Client an easier option to use to get the faker connector to work i.e. get all the examples in the repo just work "out of the box"

Thanks again, 

/Dan

**Comment by sjwiesman** [comment]
Yep, I will update the readme. In 2.4, the next release, we are shipping first-class support for including custom connectors and it will be as easy as the SQL client.

**Comment by danp11** [comment]
Great.

Den ons 6 jan. 2021 17:55Seth Wiesman <notifications@github.com> skrev:
